### PR TITLE
Porting  reviewer_browse_today to 21

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Comment by glutanimate** [comment]
Cheers!

**Comment by Arthur-Milchior** [comment]
If I may ask, will you put them on ankiweb ? I don't see them.

**Comment by glutanimate** [comment]
Yes, but these have <200 downloads after 2-3 years of being up on AnkiWeb, so I have to prioritize other tasks at the moment.

**Comment by glutanimate** [comment]
FWIW, I've just uploaded browse today. However, I also just tested Limit cards to less than one on an empty Anki config and get the following traceback:


```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'sched_advanced_newcard_limits':
Traceback (most recent call last):
  File "/home/ari/Projects/AnkiDesktop21/aqt/addons.py", line 70, in loadAddons
    __import__(dir)
  File "/home/ari/Tests/Anki/small_addons/addons21/sched_advanced_newcard_limits/__init__.py", line 9, in <module>
    from . import sched_advanced_newcard_limits
  File "/home/ari/Tests/Anki/small_addons/addons21/sched_advanced_newcard_limits/sched_advanced_newcard_limits.py", line 38, in <module>
    deck_limits.update(userOption["deck limits"])
TypeError: 'NoneType' object is not subscriptable
```

It just means that there's more to this than just the uploading. Testing these smaller add-ons takes an unproportional amount of time compared to their userbase, which is why I have to push them back in favor of other add-ons.

**Pull request merged**
